apiVersion: v1
kind: Service
metadata:
  name: sample-springboot-app-service
spec:
  selector:
    app: sample-springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
